const reviews_v2 = 
[
	/*
		{
				name: "",
				img: "",
				datePlayed: "",
				completed: false,
				stream: "",
				pros: [],
				cons: [],
				rankings: {
						gameplay: 5,
						graphics: 5,
						audio: 5,
						story: 5,
						microtransactions: 5,
						uniqueness: 5,
				},
				links: {steam: ""},
				review: ""
		},
		*/
		{
			name: "Wasteland Bites: DEMO",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3820720/7790a3e490eb9069f320d0d346ae6f687a76e590/header.jpg?t=1774983840",
				datePlayed: "2026-09-20",
				completed: false,
				stream: "https://www.youtube.com/watch?v=rK4cCRtK1BQ",
				pros: ["past paced", "solid tutorial that left me feeling equiped", "great polish"],
				cons: ["audio is a touch flat"],
				rankings: {
						gameplay: 9,
						graphics: 8,
						audio: 7,
						story: 6.5,
						uniqueness: 7,
				},
				links: {steam: "https://store.steampowered.com/app/3820720/Wasteland_Bites_Demo/"},
				review: "a fun gamer that feels like fnaf and a cooking sim made sweet unholy love, is definently a game that i want to return to at somepoint"
		},
		{
				name: "that's not my neighbor!",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3431040/header.jpg?t=1763509556",
				datePlayed: "2026-09-20",
				completed: false,
				stream: "https://www.youtube.com/watch?v=rK4cCRtK1BQ",
				pros: ["great artstyle", "unique gameplay",],
				cons: ["touch buggy", "a little repetitive"],
				rankings: {
						gameplay: 7.5,
						graphics: 7,
						audio: 6.5,
						story: 7,
						uniqueness: 9,
				},
				links: {steam: "https://store.steampowered.com/app/3431040/Thats_not_my_Neighbor/"},
				review: "a fun game that flexes a different muscle than normal, i would say it's worth a play for novelty alone"
		},
		{
				name: "stack protocol",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3937000/e3528c53a318ef1085a5f53eb53a8d02ad160459/header.jpg?t=1772652682",
				datePlayed: "2026-07-20",
				completed: true,
				stream: "https://www.youtube.com/watch?v=sxGLoTQHspw",
				pros: ["asethitally well cone game, really cohesive style that doesn't interfere with gameplay", "speedrunning board is fun"],
				cons: ["please change the camera", "can be kinda repetitive"],
				rankings: {
						gameplay: 6.5,
						graphics: 9,
						audio: 6,
						story: 6.5,
						uniqueness: 9,
				},
				links: {steam: "https://store.steampowered.com/app/3937000/Stack_Prootocol/"},
				review: "fun gamethat's really cute,but can be very tedious and the camera is really frustrating. "
		},
		{
				name: "gun frog",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3173130/17c082c5ff14655292be22031b8d57779df308d5/header.jpg?t=1765989240",
				datePlayed: "2026-07-20",
				completed: false,
				stream: "https://www.youtube.com/watch?v=STTs_9QYVSI",
				pros: ["peak indie game vibes"],
				cons: ["touch repetitive, could use more mechanical depth"],
				rankings: {
						gameplay: 8,
						graphics: 7,
						audio: 7,
						story: 6.5,
						uniqueness: 8.5,
				},
				links: {steam: "https://store.steampowered.com/app/3173130/Gun_Frog/"},
				review: "honestly probably my new aimtrainer outside ultrakill ngl"
		},
		{ 
			name: "Dusk", 
			img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/519860/20283611e9d427c4bfb5c5d23772c988df74a147/header.jpg?t=1767216306", 
			datePlayed: "2026-07-20", 
			completed: false, 
			stream: "https://www.youtube.com/watch?v=5tnS0nVnUTY", 
			pros: ["you shoot klansmen in the face"], 
			cons: ["you can't shoot more klansmen in the face"], 
			rankings: { 
				gameplay: 8,
				graphics: 6.5,
				audio: 7,
				story: 4, 
				uniqueness: 7,
			},
			links: {steam: "https://store.steampowered.com/app/519860/DUSK/"},
			review: ""
		},
		{
				name: "Meccha Chameleon",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4704690/163e2a742e5fb8e1f5d1e3a890da98f04ab809d4/header.jpg?t=1782561846",
				datePlayed: "2026-07-11",
				completed: true,
				stream: "https://www.youtube.com/watch?v=m_DMGJFckCo",
				pros: ["fun unique party game"],
				cons: ["controls are a bit clunky"],
				rankings: {
						gameplay: 8,
						graphics: 7,
						audio: 6,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/4704690/MECCHA_CHAMELEON/"},
				review: "fun party game, defo worth a play, i know basic, just play the game with friends lol"
		},
		{
				name: "nuclear nightmare",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2909110/header.jpg?t=1772607251",
				datePlayed: "2026-07-10",
				completed: false,
				stream: "https://www.youtube.com/watch?v=nCPYBepvudc",
				pros: ["unique seting", "unique context"],
				cons: ["audio balancing is kinda horrible(good audio, i just could not hear shit)", "monsters quickly fall into a quick and clear rythem", "it is clear the game has one way it expects you to do anything, and doing anything else is a waste of time/resources.", "monsters are kinda just repetitive run at you rawr monsters"],
				rankings: {
						gameplay: 6.5,
						graphics: 7,
						audio: 3,
						story: 5,
						uniqueness: 7,
				},
				links: {steam: "https://store.steampowered.com/app/2909110/Nuclear_Nightmare/"},
				review: "fun game for a one off thing, get it on sale with some friends for liek 1-2$ each adn just mess around. i can think of a lot worse things to spend 2$ on"
		},
		{
				name: "Palworld v1.0",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1623730/6912f19c43a95ff5fe514eedd35e68bf12335459/header.jpg?t=1784190284",
				datePlayed: "2026-06-09",
				completed: false,
				stream: "https://store.steampowered.com/app/1623730/Palworld/",
				pros: ["this is just what pokemon should be [maybe minus the guns]"],
				cons: ["has some indie vibes in the rough edges way", "area power scaling made no sense to me", "certain restrictions didn't feel very clear",],
				rankings: {
						gameplay: 8,
						graphics: 9,
						audio: 7,
						story: 7,
						uniqueness: 7, 
				}, 
			links: {steam: "https://www.youtube.com/watch?v=A_FOwgNxqBs"},
				review: "this is just what pokemon should have been making since 2016, if you play pokemon and think this game is bad, you're a diluted chud i'm sorry, this is just so much better. nintendo should be ashamed"
		},
		{
			name: "Megaman: PoweredUp",
				img: "https://i.ytimg.com/vi/CkFdy82kESU/maxresdefault.jpg?v=6a488959",
				datePlayed: "2026-07-03",
				completed: true,
				stream: "https://www.youtube.com/watch?v=CkFdy82kESU",
				pros: ["the best remake i've ever played", "graphics that still hold up", "fun characters", "tight gameplay", "unique and meorable bosses that don't feel cheap", "HOW THE ACTUAL HELL IS THERE LIKE 11 PLAYABLE CHARACTERS!?"],
				cons: ["the chibi artstyle really makes it feel a touch childish", "the grid/tile based levels are well done but a grid is always noticable and a touch distracting to me", "some jumps/timings feel very ackward and don't feel clear to the player"],
				rankings: {
						gameplay: 9,
						graphics: 9,
						audio: 10,
						story: 8,
						uniqueness: 10,
				},
				links: {website:"https://en.wikipedia.org/wiki/Mega_Man_Powered_Up" },
				review: "genuinely an insane reimaging of the first megaman game, making each character playable is actually insane, this game genuinely is one of if not my favorite megaman games because of how dense the game is. trying to 100% this game you could easily spend 20+ hours and except the boss rush challanges, it won't even feel that repetitive. imo a must play"
		},
		{
				name: "Tattletail",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/568090/header.jpg?t=1572988418",
				datePlayed: "2026-07-02",
				completed: true,
				stream: "https://www.youtube.com/watch?v=kjpDc5-JB_Y",
				pros: ["short in a good way", "solid atmosphere"],
				cons: ["what the fuckis this kid thinking???",],
				rankings: {
						gameplay: 9,
						graphics: 7,
						audio: 8,
						story: 6.5,
						uniqueness: 8,
				},
				links: {steam: "https://store.steampowered.com/app/568090/Tattletail/"},
				review: "tattle tail is a fantastic game that sets a premis, executes said premis, and leaves before it gets stale, boring, or repetitive. 100% the game can be really annoying and made me play the game start to finish like 3x, which isn't that bad because it's a short game, but is something i would have prefered to not do. definantly worth a play tho if you haven't played it before"
		},
		{
				name: "the finals",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2073850/61f55ef49a74c76bf9fda9ec35bc3101eeee2b3e/header.jpg?t=1783602452",
				datePlayed: "2026-06-24",
				completed: false,
				stream: "https://www.youtube.com/watch?v=9HlCwSXwHWQ",
				pros: ["a game that acutally has true destruction making the game insanely more dynamic compared to something like battlefiels/cod", "a class system where one class doens't feel like the short stick", "a decent enough variety of weapons without feeling repetitive or redundant", "you can buy old battle passes and level them so if there's any cosmetics you want that you missed you have options"],
				cons: ["the microtransactions are just transactions", "AI announcers don't add much to the game"],
				rankings: {
						gameplay: 10,
						graphics: 10,
						audio: 7,
						microtransactions: 5,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/2073850/THE_FINALS/"},
				review: "a fun forward looking fps game, the first fps game i would say that feels 'next gen' since r6 siege. the only issue is that any of the cosmetics i think are worth it are liek 10$+, making it hard to justify buying. i understand the game is free so i acknowledge that tradeoff, however the microtransactions are sorta just transactions here."
		},
		{
			name: "casualties: unknown",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4576490/907888dce73f50c48410b5ab92971a0d95776b29/header.jpg?t=1782201614",
				datePlayed: "2026-06-23",
				completed: false,
				stream: "https://www.youtube.com/watch?v=DP2Kxmbt45c",
				pros: ["asethitcally cohesive", "solid sound design", "unique health system"],
				cons: ["can be overwhelming at first", "not a good sense of what is the right path at the beginning", "poor expie :c"],
				rankings: {
						gameplay: 7,
						graphics: 7,
						audio: 7,
						story: 5,
						uniqueness: 8,
				},
				links: {steam: "https://store.steampowered.com/app/4576490/Casualties_Unknown/"},
				review: "casualties unknown is a really neat game which has a unique healthsystem that feel really overwhelming in a depressive but also entreaging way. the per limb health system is really great for making the player see things is more dimensions and really feel for the expie. the only thing i feel conflicted about is that i generally feel really bad for the expie given all the crys and messages, so on one hand i really want to do everything i can for the dood, but on the otherhand it makes me feel kinda depressed when i mess up because i don't want the lil doob hurt but my conciquences cause them too and make me feel bad :c"
		},
		{
				name: "Voices of the void",
				img: "https://img.itch.zone/aW1nLzI2NDI5MDU2LmpwZw==/original/tdJM14.jpg",
				datePlayed: "2026-04-22",
				completed: false,
				stream: "https://www.youtube.com/watch?v=8wTi9wcWAHI",
				pros: ["unique setting", "genuinely unique idea", "great atmosphere"],
				cons: ["if cleaning simulator doesn't seem appealing to you this game might be rough", "onboarding is really boring and honestly needs to be refined", "game pace is really really slow for me"],
				rankings: {
						gameplay: 3,
						graphics: 7,
						audio: 7,
						story: 3,
						uniqueness: 8,
				},
				links: {itch: "https://mrdrnose.itch.io/votv"},
				review: "votv seems like it can be a really fun game if you're a person who likes to organize and kinda have that 'cozy game' vibe but with a horror twitst, the issue is from my experience is that the gameplay is really really really slow and my 67 zoomer brain really doens't like the pacing. i feel like the tutorial also does a really bad job trying to onboard the player, basically just wall of texting them and telling them to read. i don't really have too many issues with this approach if it's short, but the issue is when you're on paragraphs it makes it a sloug. if i wanted to read i would go pick up a book, if i wanted to clean i have a living space, this game doesn't really do anything for me."
		},
		{
			name: "gmod: PROPHUNT",
				img: "https://i.ytimg.com/vi/X6dcUDgPdYM/maxresdefault.jpg?v=69e852da",
				datePlayed: "2026-04-25",
				completed: true,
				stream: "https://www.youtube.com/watch?v=X6dcUDgPdYM",
				pros: ["fun game", "tonnes of community support", "solid community", "very very creative game"],
				cons: ["an aging game engine leave it feeling a touch rough", "menu UI is jank af and is really unintuitive.", "due to being community driven the quality of maps and things vary from amazing to what the actual hell are they thinking"],
				rankings: {
						gameplay: 8,
						graphics: 7,
						audio: 6,
						uniqueness: 10,
				},
				links: {steam: "https://steamcommunity.com/sharedfiles/filedetails/?id=135509255"},
				review: "really fun mod for gmod, it will forever be fun with friends, the only issue with it is the varying quality of maps and the source 1 lighting is getting a bit dated. if those don't bother you the game is timeless :3, btw tony your maps area solid 9/10, good job *pat pat*, *gives you a jar of peanut butter*, *pat pat*"
		},
		{
			name: "Fortnite: rocket racing",
				img: "https://upload.wikimedia.org/wikipedia/en/b/b1/Fortnite_Ballistic_key_art.png",
				datePlayed: "2026-04-12",
				completed: true,
				stream: "https://www.youtube.com/watch?v=2L46EbDpDks",
				pros: ["a game from epic that isn't another shooter"],
				cons: ["gameplay is generally simple, lacks a lot of depth", "raced 3x, only got to play one map", "game is now sunset"],
				rankings: {
						gameplay: 6,
						graphics: 8,
						audio: 7,
						microtransactions: 3,
						uniqueness: 4,
				},
				links: {epic: "https://store.epicgames.com/p/fortnite"},
				review: "the game has aesthetic, but it really lacked anythiung to make the game unique or stand out. the tracks were far too forgiving with little challange, and felt more like a demo area over an actual course. little room for improvement with horrible match making made it so that the racing didn't feel rewarding or offer much intreige. without massive rewords to the mechanics there is no way in hell this would be a mario kart competitor, let along a garfield kart competitor"
		},
		{
			name: "Fortnite: ballistic",
				img: "https://upload.wikimedia.org/wikipedia/en/b/b1/Fortnite_Ballistic_key_art.png",
				datePlayed: "2026-04-12",
				completed: true,
				stream: "https://www.youtube.com/watch?v=2L46EbDpDks",
				pros: ["fortnite finally is first person", "really fun to curbstomp kids who are on the switch while you're on pc", "an ideration of cs that feels like it actually ads to the formula"],
				cons: ["lobbys are horribly balanced", "game is now dead, can no longer play", "holy immersionbreak batman"],
				rankings: {
						gameplay: 7,
						graphics: 6,
						audio: 7,
						microtransactions: 4,
						uniqueness: 6,
				},
				links: {epic: "https://store.epicgames.com/p/fortnite"},
				review: "the game was fun but either wasn't pushed hard enough or didn't resonate with the audience fortnite already had, the game can be fun, but the matchmaking, clearly unfinished maps, and agressive skins that break immersion kinda make the game feel more like walking into a gift shot rather than a co-hesive game. it would be fun if we had a CS alternative, but at the same time i understand entirely why this project has been sunset."
		},
		{
				name: "PEAK (solo)",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3527290/31bac6b2eccf09b368f5e95ce510bae2baf3cfcd/header.jpg?t=1775581133",
				datePlayed: "2026-04-11",
				completed: false,
				stream: "https://www.youtube.com/watch?v=2VeCQGkXES4",
				pros: ["aesthetically awesome", "fun customization that actually makes you wanna play to unlock things", "really fun creative biomes"],
				cons: ["rng nature of some maps make it so that some maps are far too punishing towards new players, and some settings are just brutal."],
				rankings: {
						gameplay: 8,
						graphics: 9,
						audio: 8,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/3527290/PEAK/"},
				review: "rng is the biggest pain and pleasure of this game, it makes it so that the game is unique and fresh every week, however the cost of the game being rng is that the difficulty of the map that week can vary greatly and can make or break some players with difficulty that swings really hard depending on who you are."
		},
		{
				name: "still wakes the deep",
				img: "https://i.ytimg.com/vi/qaiHz0mrnWA/maxresdefault.jpg?v=69d1d4fe",
				datePlayed: "2026-04-04",
				completed: true,
				stream: "https://www.youtube.com/watch?v=qaiHz0mrnWA",
				pros: ["beautiful game", "grounded characters", "unique premis"],
				cons: ["some sections can go on a bit too long", "some monsters feel to similar", "dlc doesn't feel liek it pays the original story well"],
				rankings: {
						gameplay: 7,
						graphics: 10,
						audio: 10,
						story: 9,
						microtransactions: 9,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/1622910/Still_Wakes_the_Deep/"},
				review: "good horror game, fantastic graphics, gameplay could use a bit more work, characters could use a little more fleshing out"
		},
		{
				name: "the notdeer stew",
				img: "https://i.ytimg.com/vi/XJ4FcIMpcco/maxresdefault.jpg?v=69d06ca5",
				datePlayed: "2026-04-03",
				completed: true,
				stream: "https://www.youtube.com/watch?v=AGDk5OA35dQ",
				pros: ["tickes a spoopy nerve"],
				cons: ["tickles a spoopy nerve"],
				rankings: {
						gameplay: 8,
						graphics: 8,
						audio: 9,
						story: 6,
						uniqueness: 8,
				},
				links: {itch: "https://roawrvideostore.itch.io/the-not-deer-stew"},
				review: "fuck this game"
		},
		{
				name: "buckshot roulette",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2835570/header.jpg?t=1783085442",
				datePlayed: "2026-04-01",
				completed: true,
				stream: "https://www.youtube.com/watch?v=AGDk5OA35dQ",
				pros: [
					"tight game loop",
					"banger music",
					"dope aesthetic",
				],
				cons: [
					"a touch repetitve",
					"not enough skill",
				],
				rankings: {
						gameplay: 8.5,
						graphics: 8.5,
						audio: 8.5,
						uniqueness: 9,
				},
				links: {steam: "https://store.steampowered.com/app/2835570/Buckshot_Roulette/"},
				review: "a fun unique game that doesn't overstay its welcome, anything 'new game plus' can be a bit repetitive"
		},
		{
				name: "cruelty squad",
				img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1388770/header.jpg?t=1740330233",
				datePlayed: "2026_03_21",
				completed: false,
				stream: "https://www.youtube.com/watch?v=CSLr4PYR3Sg",
				pros: [
					"high player expression",
					"no 'right way to play'",
				],
				cons: [
					"visuals dispite being intentional can be an eyesore to the point of being overstimulating at times",
				],
				rankings: {
						gameplay: 10,
						graphics: 7,
						audio: 8,
						story: 7,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/1388770/Cruelty_Squad/"},
				review: "fun game with intentionally bizzar visuals, most of the 'oddoties' most complain about at a glance melt away, only asterisk is some places are so agressively oversaturated i found it exhausing after a bit."
		},
		{
				name: "ultrakill layer 8 update",
				img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1229490/capsule_616x353.jpg?t=1771983912",
				datePlayed: "",
				completed: false,
				stream: "",
				pros: [
					"great gunplay",
					"diverse enemies that actually feel different",
				],
				cons: [
					"8-3 and 8-4 are just kinda bad design, 8-3 feels like filler and is just a drag without feeling that rewarding",
					"8-4 removes the whole movement side of ultrakill making the boss feel boring, generic, and just not fun. it doens't feel like it should be in ultrakill.",
					"the marksman broke :c",
				],
				rankings: {
						gameplay: 8,
						graphics: 9,
						audio: 7,
						story: 7,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/1229490/ULTRAKILL/"},
				review: ""
		},
		{
			name: "sonic boom: rise of lyric",
				img: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/wiiu_14/SI_WiiU_SonicBoomRiseOfLyric_enGB_image1600w.jpg",
				datePlayed: "2026_03_07",
				completed: false,
				stream: "",
				pros: [
					"solid artstyle (not nessisarily settings",
					"multiple playable characters",
					"strong personalities from the characters",
					"has decent animations (at times)",
				],
				cons: [
					"the worlds lack any real visual points of interest making all the areas feel bland and samesy",
					"amy and knuckles in combat (about 1/2 the gameplay) feel effectively identical, which elaves basically no reason to choose one over the other.",
					"enemies are wayyy to repetitive",
					"very clear issues due to rushing liek animations being bugged at times and just weird blackscreens, characters being where they shouldn't, etc etc",
				],
				rankings: {
						gameplay: 4,
						graphics: 7.5,
						audio: 6,
						story: 5,
						uniqueness: 7,
				},
				links: {website: "https://www.amazon.ca/Sonic-Boom-Rise-Lyric-WiiU/dp/B00KX7672U"},
				review: "the internet was too harsh on this one but it wasn't that good either... feel free to skip this one lol"
		},
		{
				name: "goblin cleanup",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2748340/96c554c074fa1f87e2f826d9b322d720cbf5ea04/capsule_616x353.jpg?t=1771262001",
				datePlayed: "2026_03_06",
				completed: false,
				stream: "https://www.youtube.com/watch?v=iV9PsdibnOw",
				pros: [
					"good artstyle",
					"good animations",
					"mechanics feel polished",
				],
				cons: [
					"the game completely lacks player agency (there's one way to do everything, the only thing that actually matters with the game is doing the thing you need to do, which there is always only 1 way to do it, maybe 2 if you are near a pit)",
					"feels repetitve really quicly",
				],
				rankings: {
						gameplay: 3,
						graphics: 9,
						audio: 6.5,
						uniqueness: 7,
				},
				links: {steam: "https://store.steampowered.com/app/2748340/Goblin_Cleanup/"},
				review: ""
		},
		{
				name: "sucker for love",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1574270/capsule_616x353.jpg?t=1730135477",
				datePlayed: "2026_02_14",
				completed: false,
				stream: "https://www.youtube.com/watch?v=tXhpl8z6hAs",
				pros: [
					"really good art",
					"charming characters",
					"IT ACTUALLY HAS GAMEPLAY",
					"hubba hubba",
				],
				cons: [
					"'rituals' can be pretty repetitive",
					"i think one of the secrets i was trying to complete was bugged",
					"ui made me think there was more story options then there actually was",
				],
				rankings: {
						gameplay:8,
						graphics: 10,
						audio: 9,
						story: 9,
						uniqueness: 9,
				},
				links: {steam: "https://store.steampowered.com/app/1574270/Sucker_for_Love_First_Date/"},
				review: ""
		},
		{
				name: "^.w.^",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4248860/788331aa47660340fd049a81963147b8343147cf/header.jpg?t=1768638130",
				datePlayed: "2026_02_14",
				completed: true,
				stream: "https://www.youtube.com/watch?v=tXhpl8z6hAs",
				pros: ["you don't have to do anything"],
				cons: ["you don't haveto do anything"],
				rankings: {
						graphics: 6,
						audio: 6,
						uniqueness: 5,
				},
				links: {steam: "https://store.steampowered.com/app/4248860/o/"},
				review: ""
		},
		{
				name: "the trolly solution",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3219410/795fb098d0271a0e663e9cc677ee22cbc5abfa99/header.jpg?t=1769932821",
				datePlayed: "2026_02_14",
				completed: false,
				stream: "https://www.youtube.com/watch?v=tXhpl8z6hAs",
				pros: [
					"comic book esc art style", 
					"a fun twist on a topic"
				],
				cons: [
					"very flat artstyle",
					"some rough edges when it ocmes to game design",
					"has some rough pacing which really hurts the gameplay",
				],
				rankings: {
						gameplay: 4,
						graphics: 6,
						audio: 4,
						uniqueness: 5,
				},
				links: {steam: "https://store.steampowered.com/app/3219410/The_Trolley_Solution/"},
				review: ""
		},
		{
				name: "fishing at the lake full of cats",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3963070/f32404c086f4383082caf3ef7206f30c511922e2/header.jpg?t=1763049979",
				datePlayed: "2026_02_14",
				completed: true,
				stream: "https://www.youtube.com/watch?v=tXhpl8z6hAs&t=12990s",
				pros: [
					"funny photobash artstyle",
					"charming fun little jokes",
					"some fun eastereggs",
				],
				cons: [
					"getting certain cats were frustraiting to the point it felt like i was doing the wrong thing ,however i just didn't align myself exactly how the game wanted me to be",
					"no replay value sadly (get it for your friends tho because it's a fun thing to watchthem experience imo lolz",
				],
				rankings: {
						gameplay: 7,
						graphics: 8,
						audio: 8,
						uniqueness: 9,
				},
				links: {steam: "https://store.steampowered.com/app/3963070/Fishing_at_the_Lake_Full_of_Cats/"},
				review: ""
		},
		{
				name: "CumMon",
				img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3965120/f611b59d08eae5638ff1c7af6c8f8f50b30b91b9/capsule_616x353.jpg?t=1758550953",
				datePlayed: "2026_02_14",
				completed: false,
				stream: "",
				pros: [
					"haha cum",
				],
				cons: [
					"game is very flat and repetitive",
					"lacks variety and you quickly hit the wall of what is 'fun'",
				],
				rankings: {
						gameplay: 4,
						graphics: 6.5,
						audio: 4,
						story: 4,
						uniqueness: 3,
				},
				links: {steam: "https://store.steampowered.com/app/3965120/CumMon/"},
				review: ""
		},
		{
				name: "chromatic conundrum",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3081690/fb6ad82908568ba61a9f5daf084f31a22e4439b7/header.jpg?t=1769947133",
				datePlayed: "",
				completed: true,
				stream: "https://www.youtube.com/watch?v=tXhpl8z6hAs&t=12990s",
				pros: [
					"very unique and fun",
					"stylistically unique",
					"one of the few times a raytracing like mechanic has actually beene used for gameplay",
				],
				cons: [
					"some solutions feel incorrect",
					"the game is only about 20ish levels long",
					"not much for music or sfx, and the ones there are, are quite repetitive",
				],
				rankings: {
						gameplay: 9,
						graphics: 9,
						audio: 5,
						uniqueness: 10,
				},
				links: {steam: "https://store.steampowered.com/app/3081690/Chromatic_Conundrum/"},
				review: ""
		},
		{
				name: "golf with your friends",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/431240/header.jpg?t=1771860670",
				datePlayed: "2026_02_13",
				completed: true,
				stream: "https://www.youtube.com/watch?v=oqVt_ByaViw&t=52s",
				pros: [
					"fun environments",
					"lots of modes to mix up replayplays",
					"maps have minor changes based on game mode which is nice",
				],
				cons: [
					"net reg can be ass",
					"certain levels will softlock you",
					"physics can be unpredictable to a point it's a die roll",
				],
				rankings: {
						gameplay: 8,
						graphics: 7.5,
						audio: 6,
						microtransactions: 8,
						uniqueness: 6.5,
				},
				links: {steam: "https://store.steampowered.com/app/431240/Golf_With_Your_Friends/"},
				review: ""
		},
		{
			name: "r6 siege: tenfold persuit (y10-s4)",
				img: "https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/6oP5pVJ4b6cq3cTwIr9hti/b2d6155ba9793eb610249b8faa1898a7/rainbow-six-siege-y10s4-meta.jpg",
				datePlayed: "",
				completed: true,
				stream: "",
				pros: [
					"the atomic interactive environments of any other multiplayer game",
					"lots of 'heros' making the game engauging and adding lots to learn",
				],
				cons: [
					"story is basically non-existant and is kinda contrived. not to mention story contriditions",
					"game is a nightmare to learn for new players",
					"locking gun access behind a battle pass is insanely cringe.",
				],
				rankings: {
						gameplay: 9,
						graphics: 8,
						audio: 5,
						story: 3,
						microtransactions: 3,
						uniqueness: 8,
				},
				links: {steam: "https://store.steampowered.com/app/359550/Tom_Clancys_Rainbow_Six_Siege/"},
				review: ""
		},
		{
				name: "choo choo charles",
				img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1766740/capsule_616x353.jpg?t=1718841444",
				datePlayed: "2026_01_24",
				completed: true,
				stream: "https://www.youtube.com/watch?v=mZjr1Q_6m7E",
				pros: [		
					"funny yet seroious",
					"decent graphics",
					"amazing atmostphere",
				],
				cons: [
					"enemies lock on wayy to long",
					"nightmare is just a pain",
					"not at tonne of replay value"

				],
				rankings: {
						gameplay: 7,
						graphics: 8,
						audio: 8,
						story: 6,
						uniqueness: 9,
				},
				links: {steam: "https://store.steampowered.com/app/1766740/ChooChoo_Charles/"},
				review: ""
		},
	/*-----------------------------------------------*/
		{
				name: "IRON LUNG",
				img: "https://i.ytimg.com/vi/bOHbe5tbhJI/hqdefault.jpg",
				datePlayed: "2026_01_29",
				completed: true,
				stream: "https://www.youtube.com/watch?v=gX3fQHqcL5c",
				pros: [
					"natural dialogue (actually)"
				],
				cons: [],
				rankings: {
					graphics: 9,
					audio: 9,
					story: 8,
					pacing: 9,
					uniqueness: 10,
				},
				links: {website: "https://ironlung.com/"},
				review: "a genuinely unique movie with an intraging environment, which kept me engauged the whole time. this isn't a youtuber movie, it's just a good movie"
		},
		{
			name: "Amnesia: rebirth",
			img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/999220/header.jpg?t=1752056337",
			datePlayed: "2026-01-24",
			completed: true,
			stream: "https://www.youtube.com/watch?v=n-Wds66nsYM",
			pros: [
				"unique environments",
				"looks great",
				"immersive gameplay",
				"physics based world"
			],
			cons: [
				"simple monsters that are repetitive",
			],
			rankings: {
					gameplay: 7,
					graphics: 9,
					audio: 9,
					story: 8,
					uniqueness: 10,
			},
			links: {steam: "https://store.steampowered.com/app/999220/Amnesia_Rebirth/"},
			review: "fun game, a touch repetitive with the enemy sections. it's generally pretty obvious when a monster about to appear 9/10 of the time if you're familiar with horror game design. thankfully the story and unique environments make up for it"
		}, 
];
export default reviews_v2;
