<script>
    let basePoints = [
        "color balance is wack (doesn't look scary)",
        "mono audio didn't hurt the game (compare with regular music)",
        "roxy is the only one who has personality",
        "the whole game has two songs (and a tonne of ambiance)",
        "you're hurt! section makes no sense (med section with vanessa)",
        "jumpscares all sound the same",
        "moon every hour makes no sense (wouldn't sun be terrified for the kids?)",
        "vanny/vanessa is a strange, boring character",
        "animation is weirdly inconsistent",
        "the ai doesn't feel like it 'outsmarts' or 'outplays' me, and i only ever die to 🧀",
        "how are the menu's unresponsive?",
        "gates being moved around makes no sense (why are you limiting me?)",
        "freddy's hands don't match in the cutscene (it's impossible for it to match)",
        "the animatronics are pretty dumb (ie, plant pot of the beginning of the game)",
        "everything is plastic",
        "there's basically no music (lots of ambiance tho)",
        "the community adds way more character to the game",
        "running back and forth so much is really annoying",
        "the game doesn't do anything interesting (outside musicman)",
        "all the security bots suck",
        "the game is: the daycare, music man, monty fight",
        "the scariest animatronic is mini-musicman",
        "the game is too open, it's hard to be surprised. (zombie problem)",
        "you can't quit out of 6am for any reason (mouse issue on nov5th)",
        "how can greggory kick chika away but when i get caught by her i'm just screwed?",
        "why does every animatronic spawn behind you?",
        "why does bonnies feet have lines spilling over?",
        "the secret area has a clear lighting glitch",
        "why are some doors blocked so you need freddy?",
        "why does freddy jumpscare you when you run out of power?",
        "the lotion and roxy photo at the prize counter is amazing",
        "having to re-rotate cams is very annoying (prize counter)",
        "cams are basically useless",
        "prize counter is cool, achevement was bugged tho",
        "the menu is terrible (remake with an example?)",
        "i hate the menu font",
        "multiple animatronic theory (4 is too few for this huge place)",
        "why so many helpy posters and what not when there's not a helpy anamatronic?",
        "why does the freddy door work when it's said to be broken?",
        "the planets in fazerblast are surprizingly cool",
        "the grid in the menu means nothing",
        "freddy doesn't emote (being sad/surprised at roxy)",
        "vent with first music man clearly was not playtested (e to slide)",
        "backtracking is broken (first office won't let you pass through the door cause f u)",
        "collectables are boing to get",
        "moon spawns are bullshit",
        "flashlight turning off after charging is a nice touch",
        "the weird issue of what feels like missing textures (ie save station)",
        "screens not being emissive materials",
        "when caught some animatronics will run to your position while others just spawn",
        "why is there a floor with everything burning?",
        "how they respawn animatronics when you get caught is garbage",
        "they don't make allocations for the player having fun (fazcade enterance being spotted",
        "having one collectible that makes you need to restart the game is really duchy",
        "you commonly get put into a standing state when in vents",
        "the testing in the chamber is cool (ie eyes looking), but gregg walking is annoying",
        "can't press buttons in freddy",
        "freddy doesn't emote much if at all",
        "apparently the pizza is 5 years old???",
        "the ticket bots just disappear if you follow them",
        "weird mini cutscenese (monty security office)",
        "did i mention i hate the security bots?",
        "monty mini golf is very weird physics wise",
        "monty just despawning after you take his claws",
        "greggory white tile on finger",
        "nothing is actually happening with the head when you repair it",
        "there are few high points in the game",
        "i don't thinki would dislike the game so much if it ran good",
    ]

    const ruinPoints = [
        "starting here",
        "ROXIE RADIO",
        "ladder camera pivot is rly weird",
        "an actually interesting door puzzle?!",
        "actaully gives me the spookes?",
        "why didn't monty kill cas?",
        "more security bots",
        "helpi sounds like issabelle",
        "worried that the mask will be confusing, how does it work?",
        "monty golf at a very innapropriate time lmao",
        "discriptions on items are great",
        "CALLING IT EARLY, 'turn off security nodes' is just afton using greggles voice",
        "it's great they added a 2012 mobile game into fnaf (not sarcasm)",
        "the mask is the one ring to rule them all?",
        "i like how speedy monty is now (major contrast from before)",
        "what is the pattern of the 'child nodes' and random objects?",
        "freddy charge station is genuinely funny",
        "how are the animatronics getting power?",
        "how much later is this?",
        "giant endo coming through the theatre is really kewl",
        "i hate how helpi tells you to take the mask off (literally what else could you do?)",
        "how do the gondolas conviently run out when she gets here? did they have exactly the amount needed to run for like 5 years until she showed up",
        "chika going for a RIDE",
        "this version of roxy sucks :c",
        "prop hunt gets boring fast",
        "i like how electricity is convienient to the plot",
        "why the fuck did the go cart try ramming me?",
        "THEY GAVE ROXY PERSONALITY",
        "roxy is pissed at greggory (so why did those other jumpscares kill her?",
        "mini music man death makes way more sense",
        "i like how they make you figure out the mini music man thing",
        "william afton in this dlc is not scary lmao kek",
        "i like and hate how you can't look around in AR mode",
        "princess quest room kinda a let down",
        "the prototype freddy thing was actaully pretty cool in a 'the thing' kinda way",
        "how was roxy under that forklift???",
        "cassy crying is a nice touch",
        "the roxy save is dope AF",
        "the ending was a flap",
        // replay
        "how you get the mask is kinda dumb",
    ]
</script>

<div>
    <h1> Five Nights At Freddys </h1>
    <h2> Security Breach </h2>
    <h3> The Only Souls Are In The Animatronics </h3>
    <ul>
        {#each basePoints as idea}
            <li><a href='#${idea}'>{idea}</a></li>
        {/each}
    </ul>
    <ul>
        {#each ruinPoints as idea}
            <li><a href='#${idea}'>{idea}</a></li>
        {/each}
    </ul>
</div>
